name: models
description: Domain entities and JSON serializable data transfer objects.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  core:
    path: ../core
  equatable: ^2.0.7

dev_dependencies:
  test: ^1.25.8
