name: design_system
description: Premium Figma-quality 3D SaaS design system, glassmorphism, tokens, and reusable widgets.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  models:
    path: ../models
  firebase_repository:
    path: ../firebase_repository
  services:
    path: ../services
  google_fonts: ^6.2.1

flutter:
  assets:
    - assets/images/

dev_dependencies:
  flutter_test:
    sdk: flutter
