<?php

namespace App\AI\Enums;

enum FallbackReason: string
{
    case NONE = 'NONE';
    case LOCAL_MODEL_UNAVAILABLE = 'LOCAL_MODEL_UNAVAILABLE';
    case LOCAL_MODEL_UNSUPPORTED = 'LOCAL_MODEL_UNSUPPORTED';
    case CONTEXT_TOO_COMPLEX = 'CONTEXT_TOO_COMPLEX';
    case LOCAL_INFERENCE_FAILURE = 'LOCAL_INFERENCE_FAILURE';
    case USER_POLICY_ALLOWED = 'USER_POLICY_ALLOWED';
}
